// Recall · StackRepository. Stack generation is backend-authoritative through
// `generate_stack_rpc`; mobile never chooses stack membership or item order.
// Completion still updates the stack row and triggers server-side XP/achievements.

import '../models/models.dart';
import '../services/supabase_service.dart';
import 'base_repository.dart';

typedef StackBuildResult = ({
  Stack? stack,
  List<StackItem> items,
  bool existing,
  String? reason,
});

class StackRepository extends BaseRepository {
  StackRepository(SupabaseService supabase) : super(supabase, 'stacks');

  /// The single active stack for the user (enforced unique by 00003), or null.
  Future<Stack?> fetchActive(String userId) => guard(() async {
        final row = await supabase
            .from('stacks')
            .select()
            .eq('user_id', userId)
            .eq('status', StackStatus.active.wire)
            .maybeSingle();
        return row == null ? null : Stack.fromJson(row);
      });

  Future<StackBuildResult> generate({
    List<String>? scopeBucketIds,
    bool ahead = false,
    int? seed,
  }) =>
      guard(() async {
        final result = await supabase.rpc(
          'generate_stack_rpc',
          params: {
            'scope_bucket_ids': scopeBucketIds,
            'ahead': ahead,
            'seed': seed,
          },
        );
        return _parseStackBuildResult(asJsonMap(result));
      });

  /// Compatibility wrapper for older callers; still delegates to backend RPC.
  Future<Stack> create(String userId, List<String> scopeBucketIds) =>
      guard(() async {
        final result = await generate(scopeBucketIds: scopeBucketIds);
        final stack = result.stack;
        if (stack == null) {
          throw StateError(result.reason ?? 'No stack generated by backend.');
        }
        return stack;
      });

  Future<void> updateStatus(String stackId, StackStatus status) =>
      guard(() async {
        final changes = <String, dynamic>{'status': status.wire};
        if (status == StackStatus.completed) {
          changes['completed_at'] = DateTime.now().toUtc().toIso8601String();
        }
        await supabase.from('stacks').update(changes).eq('id', stackId);
      });

  Future<List<StackItem>> fetchItems(String stackId) => guard(() async {
        final rows = await supabase
            .from('stack_items')
            .select()
            .eq('stack_id', stackId)
            .order('position', ascending: true);
        return mapList(rows, StackItem.fromJson);
      });

  /// Stack items are created by `generate_stack_rpc`; this method only exists to
  /// fail fast if legacy code tries to write client-selected items.
  Future<List<StackItem>> addItems(List<StackItem> items) => guard(() async {
        throw UnsupportedError(
          'stack_items are backend-authoritative; call generate() instead.',
        );
      });

  Future<void> markItemReviewed(String itemId) => guard(() async {
        await supabase
            .from('stack_items')
            .update({'reviewed': true}).eq('id', itemId);
      });

  StackBuildResult _parseStackBuildResult(Map<String, dynamic> json) {
    final rawItems = json['items'];
    return (
      stack: json['stack'] == null
          ? null
          : Stack.fromJson(asJsonMap(json['stack'])),
      items: rawItems is List
          ? rawItems.map((i) => StackItem.fromJson(asJsonMap(i))).toList()
          : const <StackItem>[],
      existing: asBool(json['existing']),
      reason: asStringOrNull(json['reason']),
    );
  }
}
